language: cpp
sudo: false

env:
  - EIGEN3_INCLUDE_DIR=include

compiler:
  - gcc
  # Clang compilation with Boost is currently broken for the version of Boost available on TravisCI. See:
  # http://stackoverflow.com/questions/11302758/error-while-copy-constructing-boostshared-ptr-using-c11
  # - clang

cache:
  apt: true

addons:
  apt:
    packages:
      - libboost-dev
      - libhdf5-serial-dev

before_script:
  - mkdir build
  - cd build
  - hg clone https://bitbucket.org/eigen/eigen
  - mv eigen/Eigen ../include/Eigen
script:
  - cmake ..
  - make
