language: cpp
sudo: false

env:
  - EIGEN3_INCLUDE_DIR=include

compiler:
  - gcc
  - clang

cache:
  apt: true

addons:
  apt:
    packages:
      - libboost-dev
      - libhdf5-serial-dev

before_script:
  - mkdir build
  - cd build
  - hg clone https://bitbucket.org/eigen/eigen
  - mv eigen/Eigen ../include/Eigen
script:
  - cmake ..
  - make
